### ISSUE TITLE
Difference to https://github.com/jilion/useragent ?

### ISSUE THREAD

**Issue by ghost** [kevinelliott/agent_orange#23]
Hey, I'm looking for a useragent parser for my rails app, I'm looking at your project and this one: https://github.com/jilion/useragent

What would you say agent_orange does better compared to https://github.com/jilion/useragent?

**Comment by kevinelliott** [comment]
agent_orange follows an object-focused approach to managing the parsed information (Platform, Device, etc) instead of a single object context. It's debatable which is more useful, but agent_orange certainly does parse out versions for each layer, rather than simply present a string containing a combination of the information.

useragent does include some additional information, such as languages, and seems to offer a per-browser regex matching mechanism, where with agent_orange we have tried to provide a more holistic approach by matching keywords and determining positioning/ordering of items to hopefully allow a more generic way of detecting items.

agent_orange is still relatively young in comparison to useragent, but it's got some forward momentum and hopefully will continue to improve on a regular basis.
